name: actions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ${{ matrix.config.vm_image }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Ubuntu 20.04
            vm_image: ubuntu-20.04
          - name: Ubuntu 22.04
            vm_image: ubuntu-22.04
          - name: MacOS 11
            vm_image: macos-11
          - name: MacOS 12
            vm_image: macos-12

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install
        run: ./install.sh
